Repository microsoft/GSL, pull requests merged in 2020-08, with the labels that each got.

#868 Search for GoogleTest via pkg-config first
  tests/CMakeLists.txt
Labels: investigating

#676 fix requirement on not_null template
  include/gsl/pointers
Labels: open

#807 Add a table of features
  README.md
Labels: investigating, open

#720 Fix finally when passing a non const lvalue invokable thing
  include/gsl/gsl_util
  tests/utils_tests.cpp
Labels: open
