Repository microsoft/GSL, pull requests merged in 2024-12, with the labels that each got.

#1174 Fix SFINAE on `gsl::owner`.
  include/gsl/pointers
Labels: Type: Bug, Status: Review Needed

#1175 fix: direct-init const ref instead of list-init
  include/gsl/pointers
Labels: Priority: Medium, Type: Bug, Status: Review Needed

#1160 introduce gsl::swap for swapping gsl::not_null
  docs/headers.md
  include/gsl/pointers
  include/gsl/util
  tests/CMakeLists.txt
  tests/pointers_tests.cpp
Labels: Priority: Low, Type: Enhancement, Status: In Progress

#1176 Force unit tests for byte to use GSL implementation
  tests/byte_tests.cpp
Labels: Type: Bug, Status: Review Needed

#1177 Better use of std::enable_if
  docs/headers.md
  include/gsl/byte
  include/gsl/pointers
  tests/byte_tests.cpp
  tests/pointers_tests.cpp
  tests/span_compatibility_tests.cpp
Labels: Type: Bug, Status: Review Needed

#1179 strict_not_null for unique_ptr
  include/gsl/pointers
  tests/notnull_tests.cpp
  tests/pointers_tests.cpp
  tests/strict_notnull_tests.cpp
Labels: Type: Bug
